# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cTQF1y1XvrcQ2VhbQ-esAiCLtHPynv2n
"""

def josephus(num, rem):
    lst = []
    remlst = []
    for i in range(1, num + 1):
        lst.append(i)

    cnt = 1
    while len(lst) != 1:
        for i in lst:
            if cnt % rem == 0:
                remlst.append(i)
            cnt += 1

        for j in remlst:
            lst.remove(j)
            remlst = []

    return lst[0] - 1


button = int(input("평일 당직을 구하려면 0, 주말 당직을 구하려면 1을 입력해주세요 : "))

if button == 0 :
  num = int(input("총 사람 수를 입력해주세요(5명이상일 때 중복 없이 평일 당직 근무가 가능합니다.) : "))
  rem = int(input("Constant Factor로 설정할 정수를 입력해주세요 : "))
  nlst = []

  for i in range(1, num + 1):
    nlst.append(input("이름을 입력하세요 : "))
  a = josephus(num, rem)
  print("--------- 평일 당직 근무 일정표 입니다. ---------")
  print("월 : ", nlst[a])
  print("화 : ", nlst[(a + rem) % num])
  print("수 : ", nlst[(a + rem + rem) % num])
  print("목 : ", nlst[(a + rem + rem + rem) % num])
  print("금 : ", nlst[(a + rem + rem + rem + rem) % num])

elif button == 1 :
  num = int(input("총 사람 수를 입력해주세요(2명이상일 때 중복 없이 주말 당직 근무가 가능합니다.) : "))
  rem = int(input("Constant Factor로 설정할 정수를 입력해주세요 : "))
  nlst = []

  for i in range(1, num + 1):
    nlst.append(input("이름을 입력하세요 : "))
  a = josephus(num, rem)
  print("--------- 주말 당직 근무 일정표 입니다. ---------")
  print("토 : ", nlst[a])
  print("일 : ", nlst[(a + rem) % num])

else :
  print("0 또는 1을 입력해주세요.")